[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.8"
=======
requires-python = ">=3.12"
>>>>>>> 6042af77fbb4270367cb3e1e35ec5799e36481a5
dependencies = [
    "fastapi>=0.116.1",
]
